apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-client-ip

  labels:
    app: api-client-ip

spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate

  replicas: 1

  selector:
    matchLabels:
      app: api-client-ip

  template:
    metadata:
      labels:
        app: api-client-ip

    spec:
      terminationGracePeriodSeconds: 30

      containers:
      - name: api-client-ip
        image: "francoisaster/api-client-ip:d7792c8765b2671b35b6ce6cd23eeeffadc146d7"
        imagePullPolicy: Always
        command: ["dumb-init", "--"]
        args: ["node", "index.js"]

        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        resources:
          requests:
            cpu: "0.05"
            memory: 10Mi
          limits: 
            memory: 15Mi
            cpu: "0.05"
---
apiVersion: v1
kind: Service
metadata:
  name: api-client-ip
  labels:
    app: api-client-ip
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: api-client-ip

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-client-ip-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`$HOST_INGRESS`)
    kind: Rule
    services:
    - name: api-client-ip
      port: 80